app_name: ise--y2--b3--project
repo_ssh_url: git@github.com:mikeyfennelly1/ise--y2--b3--project.git
gh_pull_key_file: /home/mfennelly/.ssh/ansible_github_pull_key
repo_pull_dest: /srv/app
# api-gateway
nginx_port: 8080
nginx_server_name: localhost
# nats
nats_port: 4222
# collector
collector_listen_port: 8081
collector_log_level: INFO
# web-app
web_app_port: 8082
postgres_port: 5432
postgres_user: b3user
postgres_db: b3db