# Ansible Playbook for deploying microservices to coruscant VM.
#
# The purpose of this playbook is to enable us to do the equivalent of
# a `helm apply` on our infrastructure, so that the version of application
# images can develop asymmetrically, and application releases not be coupled
# to deployments.
#
# Note that you must have permissions to SSH into the VM to be able
# to execute this playbook.

- name: Deploy Applications to vm10
  hosts: vm10
  become: yes
  vars_files:
    - vars/app_values.yml
    - vars/secrets.yml

  tasks:
    - name: Forward port 5030 to 8080
      ansible.builtin.command: >
        iptables -t nat -A PREROUTING -p tcp --dport 5030 -j REDIRECT --to-port 8080
      become: true

    - name: Ensure iptables directory exists
      ansible.builtin.file:
        path: /etc/iptables
        state: directory
        owner: root
        group: root
        mode: '0755'
      become: true

    - name: Save iptables rules
      ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
      become: true

    - name: Remove conflicting containerd.io
      apt:
        name: containerd.io
        state: absent

    - name: Install docker.io
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull parent repo
      ansible.builtin.git:
        repo: "{{ repo_ssh_url }}"
        dest: "{{ repo_pull_dest }}"
        version: "main"
        accept_hostkey: yes
        recursive: no
      environment:
        GIT_SSH_COMMAND: "ssh -i {{ gh_pull_key_file }} -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new"

    - name: Write .env file
      ansible.builtin.copy:
        dest: "{{ repo_pull_dest }}/.env"
        content: |
          NGINX_PORT={{ nginx_port }}
          NGINX_SERVER_NAME={{ nginx_server_name }}
          NATS_PORT={{ nats_port }}
          COLLECTOR_LISTEN_PORT={{ collector_listen_port }}
          COLLECTOR_LOG_LEVEL={{ collector_log_level }}
          WEB_APP_PORT={{ web_app_port }}
          POSTGRES_PASSWORD={{ postgres_password }}
          POSTGRES_USER={{ postgres_user }}
          POSTGRES_DB={{ postgres_db }}
          POSTGRES_PORT={{ postgres_port }}
          POSTGRES_HOST=db

    - name: Stop old containers
      community.docker.docker_compose_v2:
        project_src: "{{ repo_pull_dest }}"
        state: absent

    - name: Pull latest images
      community.docker.docker_compose_v2:
        project_src: "{{ repo_pull_dest }}"
        pull: always

    - name: Start stack
      community.docker.docker_compose_v2:
        project_src: "{{ repo_pull_dest }}"
        state: present
