# The purpose of this inventory is to describe the nodes that our application
# runs on, and the required auth resources to access those nodes.
[vm10]
vm10 ansible_host=200.69.13.70 ansible_user=mfennelly ansible_ssh_private_key_file=~/.ssh/student_vm_10 ansible_port=2211
