#!/usr/bin/env bash
# source-dep-report.sh
#
# For each package in the kds runtime closure, trace it back to its upstream
# source: find the Nix derivation (.drv) that built it, extract the source
# store path on the host, and pull the upstream URL from the derivation env.
#
# Usage:
#   ./scripts/source-dep-report.sh [path-to-kds-binary] [output-file]
#
# Defaults:
#   binary  -> ./build/kds/kds
#   output  -> ./out/source-dep-report.md
#
# Requires: nix-store, ldd, awk, grep, sort

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${SCRIPT_DIR}/.."

BINARY="${1:-${PROJECT_ROOT}/build/kds/kds}"
OUT_DIR="${PROJECT_ROOT}/out"
OUTPUT="${2:-${OUT_DIR}/source-dep-report.md}"

# ─── sanity checks ────────────────────────────────────────────

if [[ ! -f "${BINARY}" ]]; then
    printf "ERROR: binary not found: %s\n" "${BINARY}" >&2
    printf "       Run 'task build' first.\n" >&2
    exit 1
fi

if ! command -v nix-store &>/dev/null; then
    printf "ERROR: nix-store not found — run this inside 'devbox shell'\n" >&2
    exit 1
fi

mkdir -p "${OUT_DIR}"

# ─── helpers ──────────────────────────────────────────────────

# Strip the Nix hash prefix from a store path name.
# /nix/store/abc123-openssl-3.6.1  ->  openssl-3.6.1
pkg_name() {
    basename "$1" | sed 's/^[a-z0-9]\{32\}-//'
}

# Extract the upstream source URL from a .drv file.
# .drv files are ATerm text; env vars are encoded as ("key","value") pairs.
# fetchurl and fetchFromGitHub both write their URL into "url" or "urls".
drv_source_url() {
    local drv="$1"
    local url

    # Try "url" key first, then "urls"
    url=$(command grep -oP '(?<=\("url",")[^"]+' "${drv}" 2>/dev/null | head -1) && \
        { [[ -n "${url}" ]] && echo "${url}"; return; }

    url=$(command grep -oP '(?<=\("urls",")[^"]+' "${drv}" 2>/dev/null | head -1) && \
        { [[ -n "${url}" ]] && echo "${url}"; return; }

    echo "—"
}

# Find the source store path that was the input to a derivation.
# This is the downloaded tarball/repo, usually named *-source.
drv_source_store_path() {
    local drv="$1"
    nix-store --query --inputs "${drv}" 2>/dev/null \
        | command grep -E -- '-source$' \
        | head -1 \
        || echo "—"
}

# ─── collect closure ──────────────────────────────────────────

printf "Collecting runtime closure for %s...\n" "${BINARY}"

closure=$(ldd "${BINARY}" \
    | awk '$2=="=>" && $3~/^\/nix\/store/ { n=split($3,a,"/"); print "/nix/store/"a[4] }' \
    | sort -u \
    | xargs nix-store --query --requisites \
    | sort -u)

pkg_count=$(echo "${closure}" | wc -l | tr -d ' ')
printf "Found %s packages in closure.\n" "${pkg_count}"

# ─── build report ─────────────────────────────────────────────

printf "Tracing derivations and source paths...\n"

{
    printf "# kds Runtime Dependency Source Report\n\n"
    printf "Binary: \`%s\`\n\n" "${BINARY}"
    printf "Total packages in closure: **%s**\n\n" "${pkg_count}"
    printf "| Package | Store Output Path | Derivation (.drv) | Source Store Path | Upstream URL |\n"
    printf "|---|---|---|---|---|\n"

    while IFS= read -r store_path; do
        name=$(pkg_name "${store_path}")

        deriver=$(nix-store --query --deriver "${store_path}" 2>/dev/null || echo "")

        if [[ -z "${deriver}" || "${deriver}" == "unknown-deriver" ]]; then
            drv_display="— (no deriver)"
            src_path="—"
            upstream_url="—"
        else
            drv_display="\`$(basename "${deriver}")\`"

            # The deriver for a runtime output is itself a .drv — but the URL
            # lives in the *source* derivation that fed into it. Walk one level
            # up: find the fetch .drv among the inputs.
            fetch_drv=$(nix-store --query --inputs "${deriver}" 2>/dev/null \
                | command grep '\.drv$' \
                | while IFS= read -r input_drv; do
                    url=$(drv_source_url "${input_drv}")
                    [[ "${url}" != "—" ]] && echo "${input_drv}" && break
                  done \
                | head -1 || echo "")

            if [[ -n "${fetch_drv}" ]]; then
                upstream_url=$(drv_source_url "${fetch_drv}")
                src_path=$(drv_source_store_path "${deriver}")
            else
                # Fall back to checking the deriver itself
                upstream_url=$(drv_source_url "${deriver}")
                src_path=$(drv_source_store_path "${deriver}")
            fi
        fi

        printf "| %s | \`%s\` | %s | \`%s\` | %s |\n" \
            "${name}" "${store_path}" "${drv_display}" "${src_path}" "${upstream_url}"

    done <<< "${closure}"

    printf "\n---\n"
    printf "_Generated by \`scripts/source-dep-report.sh\`_\n"

} > "${OUTPUT}"

printf "Report written to %s\n" "${OUTPUT}"
