#!/usr/bin/env bash
set -e

VERBOSE=${VERBOSE:-false}

# Function to run tasks with gum
run_task() {
    local label="$1"
    local cmd="$2"

    if [ "$VERBOSE" = "true" ]; then
        gum log --level info "Starting $label..."
        eval "$cmd"
    else
        if gum spin --spinner dot --title "$label..." -- bash -c "$cmd" > /tmp/kingdom_task.log 2>&1; then
            gum style --foreground 2 "✔ $label"
        else
            gum style --foreground 1 "✘ $label failed"
            tail -n 20 /tmp/kingdom_task.log
            exit 1
        fi
    fi
}

# 1. Format Check
run_task "Checking code formatting" "find . -name '*.cc' -o -name '*.hh' -o -name '*.hpp' | grep -v 'build/' | xargs clang-format --dry-run --Werror"

# 2. Linting (Clang-Tidy)
# Note: Clang-tidy requires a compilation database (compile_commands.json)
# We ensure it's generated by running cmake
run_task "Preparing compilation database" "cmake -B build -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
run_task "Running clang-tidy" "cmake --build build --target kds -- -k 0" # CMake config has clang-tidy enabled
