# The purpose of this inventory is to describe the nodes that our application
# runs on, and the required auth resources to access those nodes.
[configure_vm]
updakingdom ansible_host=200.69.13.70 ansible_user=mikey ansible_ssh_private_key_file=~/.ssh/student_vm_10 ansible_port=2209
[deployment_vm]
updakingdom ansible_host=200.69.13.70 ansible_user=deployment ansible_ssh_private_key_file=~/.ssh/deployment_updakingdom ansible_port=2209
