name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Kingdom
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Make build script executable
        run: chmod +x ./scripts/build.sh

      - name: Build with Nix
        run: ./scripts/build.sh

