name: build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'kds/**'
      - 'kdctl/**'
      - 'libkd/**'
      - 'cmake/**'
      - 'CMakeLists.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Make build script executable
        run: chmod +x ./scripts/build.sh

      - name: Build with Nix
        run: nix develop --command bash ./scripts/build.sh
