name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jetpack-io/devbox-action@v0.12.0
      - name: Run CI Suite
        run: devbox run ./scripts/ci.sh
        env:
          VERBOSE: false
